import type { LessonMeta } from "@/types/lesson";

export const lessonConfig: LessonMeta[] = [
  {
    slug: "what-is-money",
    title: "What Is Money?",
    summary: "Trace why societies adopt money and what properties make it useful.",
    duration: "8 min",
    order: 1,
    section: "Foundations",
  },
  {
    slug: "the-problem-with-traditional-money",
    title: "The Problem With Traditional Money",
    summary: "See where inflation, intermediaries, and changing rules make modern money fragile.",
    duration: "9 min",
    order: 2,
    section: "Foundations",
  },
  {
    slug: "what-is-bitcoin",
    title: "What Is Bitcoin?",
    summary: "Learn the core idea behind a scarce, open monetary network.",
    duration: "12 min",
    order: 3,
    section: "Foundations",
  },
  {
    slug: "who-created-bitcoin",
    title: "Who Created Bitcoin?",
    summary: "Understand Satoshi Nakamoto's role and why Bitcoin was built to outlive its founder.",
    duration: "7 min",
    order: 4,
    section: "Foundations",
  },
  {
    slug: "why-does-bitcoin-matter",
    title: "Why Does Bitcoin Matter?",
    summary: "Explore why scarcity, openness, and self-custody make Bitcoin a serious monetary idea.",
    duration: "8 min",
    order: 5,
    section: "Foundations",
  },
  {
    slug: "how-bitcoin-works-simple-view",
    title: "How Bitcoin Works (Simple View)",
    summary: "Learn the basic flow of transactions, blocks, and verification without technical overload.",
    duration: "9 min",
    order: 6,
    section: "Core Concepts",
  },
  {
    slug: "the-blockchain-explained",
    title: "The Blockchain Explained",
    summary: "Understand how blocks link together and why that shared record matters.",
    duration: "8 min",
    order: 7,
    section: "Core Concepts",
  },
  {
    slug: "what-makes-bitcoin-secure",
    title: "What Makes Bitcoin Secure?",
    summary: "See how incentives, verification, and decentralization work together to protect the network.",
    duration: "9 min",
    order: 8,
    section: "Core Concepts",
  },
  {
    slug: "why-bitcoin-is-scarce",
    title: "Why Bitcoin Is Scarce (21 Million)",
    summary: "Explore the supply cap and why predictable issuance is central to Bitcoin's design.",
    duration: "8 min",
    order: 9,
    section: "Core Concepts",
  },
  {
    slug: "decentralisation-explained",
    title: "Decentralisation Explained",
    summary: "Learn what decentralization means in practice and why it matters for money.",
    duration: "8 min",
    order: 10,
    section: "Core Concepts",
  },
  {
    slug: "what-is-a-bitcoin-wallet",
    title: "What Is a Bitcoin Wallet?",
    summary: "Learn what a wallet really does and why it is about keys, not coins sitting in an app.",
    duration: "8 min",
    order: 11,
    section: "Wallets & Ownership",
  },
  {
    slug: "custodial-vs-non-custodial-wallets",
    title: "Custodial vs Non-Custodial Wallets",
    summary: "Compare convenience and control so you can understand the main wallet tradeoff.",
    order: 12,
    duration: "8 min",
    section: "Wallets & Ownership",
  },
  {
    slug: "private-keys-explained",
    title: "Private Keys Explained",
    summary: "See why private keys define ownership and why protecting them is everything.",
    duration: "9 min",
    order: 13,
    section: "Wallets & Ownership",
  },
  {
    slug: "seed-phrases",
    title: "Seed Phrases",
    summary: "Understand what a recovery phrase is, why it matters, and how beginners should treat it.",
    duration: "8 min",
    order: 14,
    section: "Wallets & Ownership",
  },
  {
    slug: "how-to-store-bitcoin-safely",
    title: "How to Store Bitcoin Safely",
    summary: "Learn the core habits that keep bitcoin secure over the long term.",
    duration: "9 min",
    order: 15,
    section: "Wallets & Ownership",
  },
  {
    slug: "how-transactions-work",
    title: "How Transactions Work",
    summary: "Learn the basic lifecycle of a Bitcoin transaction from signing to confirmation.",
    duration: "11 min",
    order: 16,
    section: "Transactions",
  },
  {
    slug: "what-are-fees",
    title: "What Are Fees?",
    summary: "Understand why fees exist, what they pay for, and why they rise and fall.",
    duration: "9 min",
    order: 17,
    section: "Transactions",
  },
  {
    slug: "confirmations-explained",
    title: "Confirmations Explained",
    summary: "See why confirmations matter and how confidence increases as more blocks are added.",
    duration: "8 min",
    order: 18,
    section: "Transactions",
  },
  {
    slug: "sending-and-receiving-bitcoin",
    title: "Sending and Receiving Bitcoin",
    summary: "Walk through the basic steps of receiving and sending bitcoin correctly.",
    duration: "8 min",
    order: 19,
    section: "Transactions",
  },
  {
    slug: "common-transaction-mistakes",
    title: "Common Transaction Mistakes",
    summary: "Learn the avoidable errors beginners make when moving bitcoin.",
    duration: "8 min",
    order: 20,
    section: "Transactions",
  },
  {
    slug: "what-is-mining",
    title: "What Is Mining?",
    summary: "Understand what miners do and why mining is part of Bitcoin's operation.",
    duration: "9 min",
    order: 21,
    section: "Mining & Network",
  },
  {
    slug: "proof-of-work-explained",
    title: "Proof of Work Explained",
    summary: "Learn why Bitcoin uses Proof of Work and how it helps secure the ledger.",
    duration: "8 min",
    order: 22,
    section: "Mining & Network",
  },
  {
    slug: "why-miners-exist",
    title: "Why Miners Exist",
    summary: "See how miners fit into Bitcoin's incentive structure and why the network needs them.",
    duration: "8 min",
    order: 23,
    section: "Mining & Network",
  },
  {
    slug: "difficulty-and-hash-rate",
    title: "Difficulty and Hash Rate",
    summary: "Understand how Bitcoin adjusts block production and what hash rate signals about the network.",
    duration: "8 min",
    order: 24,
    section: "Mining & Network",
  },
  {
    slug: "energy-and-bitcoin",
    title: "Energy and Bitcoin",
    summary: "Get a simple explanation of why Bitcoin uses energy and how to think about that tradeoff.",
    duration: "8 min",
    order: 25,
    section: "Mining & Network",
  },
  {
    slug: "common-bitcoin-scams",
    title: "Common Bitcoin Scams",
    summary: "Learn the classic scam patterns beginners should recognize early.",
    duration: "8 min",
    order: 26,
    section: "Safety & Mistakes",
  },
  {
    slug: "how-people-lose-bitcoin",
    title: "How People Lose Bitcoin",
    summary: "See the most common ways users lose access so you can avoid them.",
    duration: "8 min",
    order: 27,
    section: "Safety & Mistakes",
  },
  {
    slug: "exchange-risks",
    title: "Exchange Risks",
    summary: "Understand what can go wrong when bitcoin is left on third-party platforms.",
    duration: "8 min",
    order: 28,
    section: "Safety & Mistakes",
  },
  {
    slug: "phishing-and-fake-apps",
    title: "Phishing and Fake Apps",
    summary: "Learn how attackers trick users into revealing sensitive information or installing bad software.",
    duration: "8 min",
    order: 29,
    section: "Safety & Mistakes",
  },
  {
    slug: "safety-checklist",
    title: "Safety Checklist",
    summary: "Use a simple checklist to build safer habits before managing larger amounts.",
    duration: "7 min",
    order: 30,
    section: "Safety & Mistakes",
  },
  {
    slug: "security",
    title: "Security",
    summary: "Build safe habits for backups, scams, and device hygiene.",
    duration: "9 min",
    order: 31,
  },
];
