import type { LessonMeta } from "@/types/lesson";

export const lessonConfig: LessonMeta[] = [
  {
    slug: "what-is-money",
    title: "What Is Money?",
    summary: "Trace why societies adopt money and what properties make it useful.",
    duration: "8 min",
    order: 1,
    section: "Foundations",
  },
  {
    slug: "the-problem-with-traditional-money",
    title: "The Problem With Traditional Money",
    summary: "See where inflation, intermediaries, and changing rules make modern money fragile.",
    duration: "9 min",
    order: 2,
    section: "Foundations",
  },
  {
    slug: "what-is-bitcoin",
    title: "What Is Bitcoin?",
    summary: "Learn the core idea behind a scarce, open monetary network.",
    duration: "12 min",
    order: 3,
    section: "Foundations",
  },
  {
    slug: "who-created-bitcoin",
    title: "Who Created Bitcoin?",
    summary: "Understand Satoshi Nakamoto's role and why Bitcoin was built to outlive its founder.",
    duration: "7 min",
    order: 4,
    section: "Foundations",
  },
  {
    slug: "why-does-bitcoin-matter",
    title: "Why Does Bitcoin Matter?",
    summary: "Explore why scarcity, openness, and self-custody make Bitcoin a serious monetary idea.",
    duration: "8 min",
    order: 5,
    section: "Foundations",
  },
  {
    slug: "wallets",
    title: "Wallets",
    summary: "Understand keys, custody, and what a wallet actually manages.",
    duration: "10 min",
    order: 6,
  },
  {
    slug: "transactions",
    title: "Transactions",
    summary: "See how Bitcoin transactions move value and settle on-chain.",
    duration: "11 min",
    order: 7,
  },
  {
    slug: "security",
    title: "Security",
    summary: "Build safe habits for backups, scams, and device hygiene.",
    duration: "9 min",
    order: 8,
  },
];
