import type { QuizQuestion } from "@/types/quiz";

function createQuestion(
  lessonSlug: string,
  index: number,
  prompt: string,
  options: [string, string, string],
  correctAnswer: string,
  explanation: string,
): QuizQuestion {
  return {
    id: `${lessonSlug}-q${index}`,
    prompt,
    options,
    correctAnswer,
    explanation,
  };
}

export const lessonQuizConfig: Record<string, QuizQuestion[]> = {
  "what-is-money": [
    createQuestion(
      "what-is-money",
      1,
      "What problem does money solve in an economy?",
      [
        "It removes the need for trade entirely.",
        "It makes exchange easier than relying on direct barter.",
        "It guarantees every item has a fixed price forever.",
      ],
      "It makes exchange easier than relying on direct barter.",
      "Money helps people trade without needing a perfect coincidence of wants.",
    ),
    createQuestion(
      "what-is-money",
      2,
      "Which quality makes something stronger as money?",
      [
        "It is widely accepted, durable, and easy to compare.",
        "It can only be used by one small group.",
        "It changes form every time it is exchanged.",
      ],
      "It is widely accepted, durable, and easy to compare.",
      "Good money is useful because people can trust and use it consistently.",
    ),
  ],
  "the-problem-with-traditional-money": [
    createQuestion(
      "the-problem-with-traditional-money",
      1,
      "What is one core weakness of traditional money systems?",
      [
        "Their rules can change under central control.",
        "They are too scarce to ever expand.",
        "They cannot be used across banks.",
      ],
      "Their rules can change under central control.",
      "The lesson stresses that changing rules and discretionary control make fiat systems fragile.",
    ),
    createQuestion(
      "the-problem-with-traditional-money",
      2,
      "Why does inflation matter to ordinary savers?",
      [
        "It can erode purchasing power over time.",
        "It guarantees wages rise faster than prices.",
        "It makes savings more scarce automatically.",
      ],
      "It can erode purchasing power over time.",
      "If money supply grows faster than value creation, savings can buy less later.",
    ),
  ],
  "what-is-bitcoin": [
    createQuestion(
      "what-is-bitcoin",
      1,
      "What is Bitcoin at its core?",
      [
        "An open monetary network with a scarce digital asset.",
        "A private company that runs a payment app.",
        "A reward system issued by banks.",
      ],
      "An open monetary network with a scarce digital asset.",
      "Bitcoin is presented as both a network and a scarce digital form of money.",
    ),
    createQuestion(
      "what-is-bitcoin",
      2,
      "What makes Bitcoin different from a normal bank account?",
      [
        "Its rules can be verified openly instead of being controlled by one institution.",
        "It only works during stock market hours.",
        "It requires permission from a central bank for every transfer.",
      ],
      "Its rules can be verified openly instead of being controlled by one institution.",
      "Bitcoin is built around open verification rather than institutional trust alone.",
    ),
  ],
  "who-created-bitcoin": [
    createQuestion(
      "who-created-bitcoin",
      1,
      "Who is the name associated with creating Bitcoin?",
      [
        "Satoshi Nakamoto",
        "Hal Finney",
        "Vitalik Buterin",
      ],
      "Satoshi Nakamoto",
      "Bitcoin was introduced by someone using the name Satoshi Nakamoto.",
    ),
    createQuestion(
      "who-created-bitcoin",
      2,
      "Why does Bitcoin not depend on knowing Satoshi's identity today?",
      [
        "Because the rules are open and the network can run without its founder.",
        "Because Satoshi still approves every update personally.",
        "Because users do not need software to use Bitcoin.",
      ],
      "Because the rules are open and the network can run without its founder.",
      "The lesson emphasizes that Bitcoin was designed to outlive its creator.",
    ),
  ],
  "why-does-bitcoin-matter": [
    createQuestion(
      "why-does-bitcoin-matter",
      1,
      "Why do many people think Bitcoin matters?",
      [
        "It offers scarce money with open verification and self-custody.",
        "It guarantees prices only go up.",
        "It lets banks issue money faster.",
      ],
      "It offers scarce money with open verification and self-custody.",
      "Bitcoin matters because of its monetary design, not because it removes all risk.",
    ),
    createQuestion(
      "why-does-bitcoin-matter",
      2,
      "What is one important idea behind Bitcoin's value proposition?",
      [
        "Users can verify the system instead of trusting opaque rule changes.",
        "The supply expands whenever demand spikes.",
        "It only works if governments operate it directly.",
      ],
      "Users can verify the system instead of trusting opaque rule changes.",
      "The lesson frames Bitcoin as a system that reduces reliance on blind trust.",
    ),
  ],
  "how-bitcoin-works-simple-view": [
    createQuestion(
      "how-bitcoin-works-simple-view",
      1,
      "In a simple view, what happens when someone sends bitcoin?",
      [
        "A transaction updates the shared ledger according to Bitcoin's rules.",
        "A physical coin moves between two phones.",
        "A bank rewrites balances in private.",
      ],
      "A transaction updates the shared ledger according to Bitcoin's rules.",
      "Bitcoin transfers are ledger updates validated by the network.",
    ),
    createQuestion(
      "how-bitcoin-works-simple-view",
      2,
      "What role do miners play in this process?",
      [
        "They gather valid transactions into blocks.",
        "They hold every user's private keys.",
        "They decide who is allowed to own bitcoin.",
      ],
      "They gather valid transactions into blocks.",
      "Miners package valid transactions into blocks and compete to add them.",
    ),
  ],
  "the-blockchain-explained": [
    createQuestion(
      "the-blockchain-explained",
      1,
      "What is a blockchain in Bitcoin?",
      [
        "A chain of blocks that records verified transaction history.",
        "A private folder owned by exchanges.",
        "A backup file for seed phrases.",
      ],
      "A chain of blocks that records verified transaction history.",
      "The blockchain is the public record of Bitcoin's transaction history.",
    ),
    createQuestion(
      "the-blockchain-explained",
      2,
      "Why do linked blocks matter?",
      [
        "They make past history harder to change without redoing enormous work.",
        "They make transactions anonymous by default.",
        "They eliminate the need for nodes.",
      ],
      "They make past history harder to change without redoing enormous work.",
      "Linking blocks makes tampering with history much more difficult.",
    ),
  ],
  "what-makes-bitcoin-secure": [
    createQuestion(
      "what-makes-bitcoin-secure",
      1,
      "What is one reason Bitcoin is considered secure?",
      [
        "Many participants verify the rules independently.",
        "The code is hidden from the public.",
        "Only miners know transaction history.",
      ],
      "Many participants verify the rules independently.",
      "Security comes from open verification and distributed participation.",
    ),
    createQuestion(
      "what-makes-bitcoin-secure",
      2,
      "How do incentives support Bitcoin security?",
      [
        "They encourage miners and nodes to follow the rules because breaking them is costly.",
        "They let attackers reverse transactions for a fee.",
        "They remove the need for economic tradeoffs.",
      ],
      "They encourage miners and nodes to follow the rules because breaking them is costly.",
      "Bitcoin security is technical and economic at the same time.",
    ),
  ],
  "why-bitcoin-is-scarce": [
    createQuestion(
      "why-bitcoin-is-scarce",
      1,
      "Why is Bitcoin described as scarce?",
      [
        "Its supply schedule is limited and predictable.",
        "It can be printed whenever miners request more.",
        "It disappears after every transaction.",
      ],
      "Its supply schedule is limited and predictable.",
      "Scarcity comes from the fixed issuance rules and supply cap.",
    ),
    createQuestion(
      "why-bitcoin-is-scarce",
      2,
      "What does the 21 million cap represent?",
      [
        "The maximum number of bitcoin that can ever exist under the current rules.",
        "The number of users allowed on the network.",
        "The yearly number of blocks mined.",
      ],
      "The maximum number of bitcoin that can ever exist under the current rules.",
      "The cap is part of Bitcoin's monetary policy and scarcity model.",
    ),
  ],
  "decentralisation-explained": [
    createQuestion(
      "decentralisation-explained",
      1,
      "What does decentralization mean in Bitcoin?",
      [
        "No single party controls the rules or ledger on its own.",
        "Nobody verifies anything.",
        "Every user must mine blocks personally.",
      ],
      "No single party controls the rules or ledger on its own.",
      "Decentralization means power is distributed rather than concentrated.",
    ),
    createQuestion(
      "decentralisation-explained",
      2,
      "Why is decentralization important for money?",
      [
        "It reduces reliance on one trusted controller.",
        "It guarantees zero mistakes forever.",
        "It makes rules easier to change quietly.",
      ],
      "It reduces reliance on one trusted controller.",
      "The lesson frames decentralization as a protection against arbitrary control.",
    ),
  ],
  "what-is-a-bitcoin-wallet": [
    createQuestion(
      "what-is-a-bitcoin-wallet",
      1,
      "What does a Bitcoin wallet actually manage?",
      [
        "The keys needed to control bitcoin on the network.",
        "A private copy of the blockchain.",
        "A company account held by miners.",
      ],
      "The keys needed to control bitcoin on the network.",
      "A wallet is mainly about key management, not coins sitting inside an app.",
    ),
    createQuestion(
      "what-is-a-bitcoin-wallet",
      2,
      "Why is it misleading to think of a wallet like a normal money app?",
      [
        "Because the wallet controls access through keys rather than storing coins locally.",
        "Because wallets cannot show balances.",
        "Because wallets only work offline.",
      ],
      "Because the wallet controls access through keys rather than storing coins locally.",
      "The lesson emphasizes ownership through keys, not coins in a container.",
    ),
  ],
  "custodial-vs-non-custodial-wallets": [
    createQuestion(
      "custodial-vs-non-custodial-wallets",
      1,
      "What is the main tradeoff with a custodial wallet?",
      [
        "It offers convenience while another party controls the keys.",
        "It is always safer than self-custody.",
        "It removes all counterparty risk.",
      ],
      "It offers convenience while another party controls the keys.",
      "Custodial wallets are easier, but the user is trusting someone else to hold the keys.",
    ),
    createQuestion(
      "custodial-vs-non-custodial-wallets",
      2,
      "What is true of a non-custodial wallet?",
      [
        "You control the keys and carry the responsibility.",
        "The exchange can recover funds anytime without your recovery phrase.",
        "It means Bitcoin is stored entirely on your device.",
      ],
      "You control the keys and carry the responsibility.",
      "Non-custodial use gives control to the user, along with the burden of secure handling.",
    ),
  ],
  "private-keys-explained": [
    createQuestion(
      "private-keys-explained",
      1,
      "What does a private key allow you to do?",
      [
        "Authorize spending from bitcoin you control.",
        "Change Bitcoin's monetary policy.",
        "Mine blocks more quickly.",
      ],
      "Authorize spending from bitcoin you control.",
      "Private keys are the critical secret used to prove control over funds.",
    ),
    createQuestion(
      "private-keys-explained",
      2,
      "What is the safest assumption about a private key?",
      [
        "Anyone who gets it can control the associated funds.",
        "It is safe to email if you trust the recipient.",
        "It only matters for large balances.",
      ],
      "Anyone who gets it can control the associated funds.",
      "Private keys must be treated like the highest-value secret in the wallet flow.",
    ),
  ],
  "seed-phrases": [
    createQuestion(
      "seed-phrases",
      1,
      "What is a seed phrase for?",
      [
        "Recovering wallet access if the device is lost or replaced.",
        "Proving your identity to an exchange.",
        "Speeding up transaction confirmations.",
      ],
      "Recovering wallet access if the device is lost or replaced.",
      "The seed phrase is the backup path to the wallet's keys.",
    ),
    createQuestion(
      "seed-phrases",
      2,
      "How should a beginner treat a seed phrase?",
      [
        "As a highly sensitive backup that should never be casually shared or stored online.",
        "As an optional note that can be regenerated later.",
        "As something safe to screenshot for convenience.",
      ],
      "As a highly sensitive backup that should never be casually shared or stored online.",
      "The lesson stresses that the recovery phrase is extremely important to protect properly.",
    ),
  ],
  "how-to-store-bitcoin-safely": [
    createQuestion(
      "how-to-store-bitcoin-safely",
      1,
      "What is one safe storage principle?",
      [
        "Use backups and treat key material carefully.",
        "Keep everything only in one place for speed.",
        "Store seed phrases in chat apps for convenience.",
      ],
      "Use backups and treat key material carefully.",
      "Safe storage comes from deliberate backup and security habits.",
    ),
    createQuestion(
      "how-to-store-bitcoin-safely",
      2,
      "Why does safe storage matter?",
      [
        "Because self-custody gives you control, but mistakes can be irreversible.",
        "Because Bitcoin can be reset by support if lost.",
        "Because exchanges always recover funds automatically.",
      ],
      "Because self-custody gives you control, but mistakes can be irreversible.",
      "Control and responsibility come together in self-custody.",
    ),
  ],
  "how-transactions-work": [
    createQuestion(
      "how-transactions-work",
      1,
      "What is a Bitcoin transaction?",
      [
        "A signed instruction that moves control of bitcoin from one address to another.",
        "A private message between two exchanges.",
        "A shortcut for creating new bitcoin.",
      ],
      "A signed instruction that moves control of bitcoin from one address to another.",
      "Transactions are signed updates to Bitcoin's ledger.",
    ),
    createQuestion(
      "how-transactions-work",
      2,
      "What happens before a transaction is treated as settled?",
      [
        "It is broadcast, verified, and then included in blocks.",
        "It instantly becomes final when typed into a wallet.",
        "It must be approved by one central server.",
      ],
      "It is broadcast, verified, and then included in blocks.",
      "Settlement confidence grows as the network validates and confirms the transaction.",
    ),
  ],
  "what-are-fees": [
    createQuestion(
      "what-are-fees",
      1,
      "Why do Bitcoin transaction fees exist?",
      [
        "They help prioritize limited block space and reward inclusion by miners.",
        "They are a tax set by a central bank.",
        "They are paid only when a transaction fails.",
      ],
      "They help prioritize limited block space and reward inclusion by miners.",
      "Fees are part of how scarce block space is allocated.",
    ),
    createQuestion(
      "what-are-fees",
      2,
      "Why do fees rise and fall?",
      [
        "Because demand for block space changes over time.",
        "Because every wallet chooses a random fee.",
        "Because Bitcoin doubles the fee every day.",
      ],
      "Because demand for block space changes over time.",
      "When more people want on-chain settlement at once, fees tend to rise.",
    ),
  ],
  "confirmations-explained": [
    createQuestion(
      "confirmations-explained",
      1,
      "What does one confirmation mean?",
      [
        "The transaction has been included in a block.",
        "The transaction has been permanently reversed.",
        "The receiver has exported the wallet.",
      ],
      "The transaction has been included in a block.",
      "A confirmation starts once a transaction is mined into a block.",
    ),
    createQuestion(
      "confirmations-explained",
      2,
      "Why do more confirmations matter?",
      [
        "They increase confidence that reversing the transaction would be difficult.",
        "They increase the total bitcoin supply.",
        "They hide the transaction from nodes.",
      ],
      "They increase confidence that reversing the transaction would be difficult.",
      "Each additional block strengthens settlement confidence.",
    ),
  ],
  "sending-and-receiving-bitcoin": [
    createQuestion(
      "sending-and-receiving-bitcoin",
      1,
      "What should you check carefully before sending bitcoin?",
      [
        "The address, amount, and fee settings.",
        "The exchange's share price.",
        "The number of miners online.",
      ],
      "The address, amount, and fee settings.",
      "Good transaction hygiene starts with checking the critical details before sending.",
    ),
    createQuestion(
      "sending-and-receiving-bitcoin",
      2,
      "What is a good first habit when receiving bitcoin?",
      [
        "Confirm the receiving address carefully before sharing it.",
        "Reuse the same address without checking.",
        "Send a seed phrase with the address for recovery.",
      ],
      "Confirm the receiving address carefully before sharing it.",
      "Receiving safely means verifying the destination information before funds move.",
    ),
  ],
  "common-transaction-mistakes": [
    createQuestion(
      "common-transaction-mistakes",
      1,
      "Which is a common beginner transaction mistake?",
      [
        "Sending to the wrong address or rushing through details.",
        "Waiting for confirmations on a large payment.",
        "Reviewing fee settings before sending.",
      ],
      "Sending to the wrong address or rushing through details.",
      "Many mistakes happen because users rush and skip checks.",
    ),
    createQuestion(
      "common-transaction-mistakes",
      2,
      "Why are transaction mistakes serious in Bitcoin?",
      [
        "Because many errors are difficult or impossible to reverse.",
        "Because miners refund incorrect payments automatically.",
        "Because wallets always allow an undo button.",
      ],
      "Because many errors are difficult or impossible to reverse.",
      "Bitcoin emphasizes finality, so care matters before sending.",
    ),
  ],
  "what-is-mining": [
    createQuestion(
      "what-is-mining",
      1,
      "What do miners do in Bitcoin?",
      [
        "They compete to add valid blocks of transactions to the chain.",
        "They hold user seed phrases for recovery.",
        "They issue new rules without node approval.",
      ],
      "They compete to add valid blocks of transactions to the chain.",
      "Mining is the block-production process that helps secure and update Bitcoin.",
    ),
    createQuestion(
      "what-is-mining",
      2,
      "Why is mining part of Bitcoin's operation?",
      [
        "It helps order transactions and secure the ledger through Proof of Work.",
        "It hides the blockchain from the public.",
        "It replaces the need for nodes.",
      ],
      "It helps order transactions and secure the ledger through Proof of Work.",
      "Mining is tied to both transaction ordering and network security.",
    ),
  ],
  "proof-of-work-explained": [
    createQuestion(
      "proof-of-work-explained",
      1,
      "What is Proof of Work in Bitcoin?",
      [
        "A costly process miners perform to earn the right to propose blocks.",
        "A password system for exchanges.",
        "A way to store bitcoin offline.",
      ],
      "A costly process miners perform to earn the right to propose blocks.",
      "Proof of Work ties block creation to real-world cost and competition.",
    ),
    createQuestion(
      "proof-of-work-explained",
      2,
      "Why does Proof of Work matter?",
      [
        "It makes rewriting history expensive and difficult.",
        "It guarantees that nobody will ever disagree on anything.",
        "It allows unlimited block space at no cost.",
      ],
      "It makes rewriting history expensive and difficult.",
      "The lesson presents Proof of Work as part of Bitcoin's security model.",
    ),
  ],
  "why-miners-exist": [
    createQuestion(
      "why-miners-exist",
      1,
      "Why do miners exist in Bitcoin's design?",
      [
        "They are incentivized to secure the network and produce blocks.",
        "They are required to approve each wallet manually.",
        "They replace the need for market incentives.",
      ],
      "They are incentivized to secure the network and produce blocks.",
      "Miners are part of Bitcoin's incentive structure, not just a technical side feature.",
    ),
    createQuestion(
      "why-miners-exist",
      2,
      "What motivates miners to follow Bitcoin's rules?",
      [
        "Rewards only have value if the network and its rules remain credible.",
        "They can profit more by ignoring validation rules.",
        "Their main job is to keep transactions secret.",
      ],
      "Rewards only have value if the network and its rules remain credible.",
      "Mining incentives align with keeping the system functioning and trusted.",
    ),
  ],
  "difficulty-and-hash-rate": [
    createQuestion(
      "difficulty-and-hash-rate",
      1,
      "What does Bitcoin difficulty adjust?",
      [
        "How hard it is to find a valid block so blocks stay near the target interval.",
        "How many wallets are allowed on the network.",
        "How many confirmations a user must wait.",
      ],
      "How hard it is to find a valid block so blocks stay near the target interval.",
      "Difficulty helps Bitcoin maintain a stable block rhythm despite changing mining power.",
    ),
    createQuestion(
      "difficulty-and-hash-rate",
      2,
      "What does hash rate roughly indicate?",
      [
        "How much computational power is being used to mine Bitcoin.",
        "How many coins exist in circulation.",
        "How many seed phrases are active.",
      ],
      "How much computational power is being used to mine Bitcoin.",
      "Hash rate is a rough signal of the mining power securing the network.",
    ),
  ],
  "energy-and-bitcoin": [
    createQuestion(
      "energy-and-bitcoin",
      1,
      "Why does Bitcoin use energy?",
      [
        "Because Proof of Work ties network security to real-world cost.",
        "Because wallets need electricity to create more coins instantly.",
        "Because nodes must burn energy to store seed phrases.",
      ],
      "Because Proof of Work ties network security to real-world cost.",
      "The lesson presents energy use as part of Bitcoin's security tradeoff.",
    ),
    createQuestion(
      "energy-and-bitcoin",
      2,
      "What is a balanced way to think about Bitcoin and energy?",
      [
        "Consider both the cost of energy use and what that energy is securing.",
        "Ignore energy completely because all digital systems are free.",
        "Assume any energy use means the system has no purpose.",
      ],
      "Consider both the cost of energy use and what that energy is securing.",
      "The lesson argues for evaluating the tradeoff rather than using slogans.",
    ),
  ],
  "common-bitcoin-scams": [
    createQuestion(
      "common-bitcoin-scams",
      1,
      "What makes many Bitcoin scams effective?",
      [
        "They exploit trust, urgency, and confusion.",
        "They require breaking Bitcoin itself.",
        "They only target expert developers.",
      ],
      "They exploit trust, urgency, and confusion.",
      "Scams usually work through social engineering rather than protocol failure.",
    ),
    createQuestion(
      "common-bitcoin-scams",
      2,
      "Which is a safer default when something feels urgent in Bitcoin?",
      [
        "Slow down and verify before taking action.",
        "Act fast so you do not miss the opportunity.",
        "Send a test seed phrase first.",
      ],
      "Slow down and verify before taking action.",
      "Urgency is a common scam tactic, so slowing down is protective.",
    ),
  ],
  "how-people-lose-bitcoin": [
    createQuestion(
      "how-people-lose-bitcoin",
      1,
      "How do people commonly lose bitcoin?",
      [
        "By losing keys, seed phrases, or access credentials.",
        "Because the blockchain randomly deletes old coins.",
        "Because miners choose whose funds disappear.",
      ],
      "By losing keys, seed phrases, or access credentials.",
      "Loss usually comes from human error and poor backup habits.",
    ),
    createQuestion(
      "how-people-lose-bitcoin",
      2,
      "What is one way to reduce the risk of losing bitcoin?",
      [
        "Have a clear backup and recovery plan before storing larger amounts.",
        "Keep everything in one untested place.",
        "Assume you can recover funds from support later.",
      ],
      "Have a clear backup and recovery plan before storing larger amounts.",
      "Planning recovery is one of the main defenses against irreversible loss.",
    ),
  ],
  "exchange-risks": [
    createQuestion(
      "exchange-risks",
      1,
      "What is the core risk of leaving bitcoin on an exchange?",
      [
        "The exchange controls the keys, so you face counterparty risk.",
        "The bitcoin stops existing outside your account view.",
        "The network no longer confirms transactions.",
      ],
      "The exchange controls the keys, so you face counterparty risk.",
      "If the platform holds the keys, the user is trusting that platform.",
    ),
    createQuestion(
      "exchange-risks",
      2,
      "Why do exchange failures matter for Bitcoin users?",
      [
        "Users can lose access even if Bitcoin itself keeps running normally.",
        "They automatically change Bitcoin's supply cap.",
        "They only affect people using hardware wallets.",
      ],
      "Users can lose access even if Bitcoin itself keeps running normally.",
      "Exchange risk is separate from Bitcoin protocol risk.",
    ),
  ],
  "phishing-and-fake-apps": [
    createQuestion(
      "phishing-and-fake-apps",
      1,
      "What is phishing in the Bitcoin context?",
      [
        "A trick that tries to steal sensitive information or access.",
        "A mining technique for mobile devices.",
        "A way to speed up transaction settlement.",
      ],
      "A trick that tries to steal sensitive information or access.",
      "Phishing relies on deception to get secrets or approvals from the user.",
    ),
    createQuestion(
      "phishing-and-fake-apps",
      2,
      "What is a good habit for avoiding fake apps?",
      [
        "Verify the source carefully before downloading or entering any sensitive information.",
        "Search quickly and install the first result.",
        "Share your seed phrase to check if the app is real.",
      ],
      "Verify the source carefully before downloading or entering any sensitive information.",
      "Verification before install is one of the strongest protections against fake apps.",
    ),
  ],
  "safety-checklist": [
    createQuestion(
      "safety-checklist",
      1,
      "What is the purpose of a Bitcoin safety checklist?",
      [
        "To build repeatable habits before mistakes become expensive.",
        "To avoid learning how the system works.",
        "To replace the need for backups.",
      ],
      "To build repeatable habits before mistakes become expensive.",
      "A checklist helps reduce avoidable errors in high-consequence situations.",
    ),
    createQuestion(
      "safety-checklist",
      2,
      "Which mindset fits a good safety checklist?",
      [
        "Deliberate verification before action.",
        "Speed over caution.",
        "Convenience over recovery planning.",
      ],
      "Deliberate verification before action.",
      "The checklist is about discipline and consistency, not rushing.",
    ),
  ],
  "how-to-buy-bitcoin": [
    createQuestion(
      "how-to-buy-bitcoin",
      1,
      "What should a beginner understand before buying bitcoin?",
      [
        "How they will store it and what tradeoffs come with the purchase path.",
        "How to mine blocks first.",
        "How to change Bitcoin's rules.",
      ],
      "How they will store it and what tradeoffs come with the purchase path.",
      "Buying is only one step; custody and process matter too.",
    ),
    createQuestion(
      "how-to-buy-bitcoin",
      2,
      "What is a practical first step when buying bitcoin?",
      [
        "Use a reputable route and understand fees, custody, and verification requirements.",
        "Send money to whoever offers the highest promised return.",
        "Ignore withdrawal options completely.",
      ],
      "Use a reputable route and understand fees, custody, and verification requirements.",
      "The lesson emphasizes deliberate, informed buying rather than impulse.",
    ),
  ],
  "where-to-buy-bitcoin": [
    createQuestion(
      "where-to-buy-bitcoin",
      1,
      "What is one difference between exchanges and peer-to-peer buying?",
      [
        "They involve different tradeoffs around convenience, privacy, and trust.",
        "Only exchanges give you real bitcoin.",
        "Peer-to-peer trades do not use money.",
      ],
      "They involve different tradeoffs around convenience, privacy, and trust.",
      "The lesson compares purchase paths through tradeoffs, not slogans.",
    ),
    createQuestion(
      "where-to-buy-bitcoin",
      2,
      "Why does the place you buy bitcoin matter?",
      [
        "It affects costs, custody flow, and risk profile.",
        "It changes the total supply of bitcoin.",
        "It decides whether your wallet can receive funds.",
      ],
      "It affects costs, custody flow, and risk profile.",
      "Where you buy influences how the entire onboarding experience works.",
    ),
  ],
  "using-bitcoin-in-daily-life": [
    createQuestion(
      "using-bitcoin-in-daily-life",
      1,
      "What does using Bitcoin in daily life mean?",
      [
        "Applying it in real situations, not only watching the price.",
        "Only day trading every week.",
        "Replacing every payment method immediately.",
      ],
      "Applying it in real situations, not only watching the price.",
      "The lesson broadens Bitcoin beyond speculation alone.",
    ),
    createQuestion(
      "using-bitcoin-in-daily-life",
      2,
      "Why is practical use worth understanding?",
      [
        "It helps connect Bitcoin's design to actual decisions and habits.",
        "It removes the need to learn about custody.",
        "It means price volatility stops mattering.",
      ],
      "It helps connect Bitcoin's design to actual decisions and habits.",
      "Practical use turns abstract ideas into real-world judgment.",
    ),
  ],
  "storing-vs-spending": [
    createQuestion(
      "storing-vs-spending",
      1,
      "What is the key idea in storing vs spending?",
      [
        "Bitcoin can be approached differently depending on whether it is savings, payments, or both.",
        "Spending always destroys long-term value automatically.",
        "Storing means never learning how transactions work.",
      ],
      "Bitcoin can be approached differently depending on whether it is savings, payments, or both.",
      "The lesson distinguishes use cases rather than forcing one answer for everyone.",
    ),
    createQuestion(
      "storing-vs-spending",
      2,
      "Why is this distinction useful?",
      [
        "Because time horizon and purpose affect how someone uses Bitcoin.",
        "Because Bitcoin only works if never moved.",
        "Because the network changes rules based on your wallet type.",
      ],
      "Because time horizon and purpose affect how someone uses Bitcoin.",
      "The lesson links usage decisions to goals and context.",
    ),
  ],
  "long-term-thinking": [
    createQuestion(
      "long-term-thinking",
      1,
      "What does long-term thinking change in Bitcoin?",
      [
        "It changes how people interpret volatility and make decisions.",
        "It guarantees profits quickly.",
        "It removes all uncertainty from markets.",
      ],
      "It changes how people interpret volatility and make decisions.",
      "Time horizon strongly shapes judgment and behavior.",
    ),
    createQuestion(
      "long-term-thinking",
      2,
      "Why do many Bitcoin learners focus on a long-term view?",
      [
        "Because it can reduce reactive thinking and emphasize understanding.",
        "Because short-term price moves stop existing.",
        "Because Bitcoin cannot be used in the present.",
      ],
      "Because it can reduce reactive thinking and emphasize understanding.",
      "The lesson ties long-term thinking to steadier judgment.",
    ),
  ],
  "nodes-explained": [
    createQuestion(
      "nodes-explained",
      1,
      "What does a Bitcoin node do?",
      [
        "It verifies blocks and transactions against Bitcoin's rules.",
        "It stores private keys for all wallets.",
        "It guarantees profit from mining.",
      ],
      "It verifies blocks and transactions against Bitcoin's rules.",
      "Nodes are central to independent verification on the network.",
    ),
    createQuestion(
      "nodes-explained",
      2,
      "Why are nodes important?",
      [
        "They help enforce the rules without relying on one authority.",
        "They replace the need for the blockchain.",
        "They allow users to change supply whenever needed.",
      ],
      "They help enforce the rules without relying on one authority.",
      "Nodes matter because they keep verification decentralized.",
    ),
  ],
  "lightning-network-simple": [
    createQuestion(
      "lightning-network-simple",
      1,
      "What is the Lightning Network in simple terms?",
      [
        "A faster payment layer built on top of Bitcoin.",
        "A replacement for the Bitcoin blockchain.",
        "A seed phrase backup tool.",
      ],
      "A faster payment layer built on top of Bitcoin.",
      "Lightning is introduced as an additional layer for faster, cheaper payments.",
    ),
    createQuestion(
      "lightning-network-simple",
      2,
      "Why might Lightning be useful?",
      [
        "It can make smaller or faster payments more practical.",
        "It eliminates the need for Bitcoin entirely.",
        "It lets anyone change consensus rules instantly.",
      ],
      "It can make smaller or faster payments more practical.",
      "The lesson presents Lightning as a scaling and usability tool.",
    ),
  ],
  "hard-forks-vs-soft-forks": [
    createQuestion(
      "hard-forks-vs-soft-forks",
      1,
      "What is the difference between a hard fork and a soft fork?",
      [
        "They are different kinds of rule changes with different compatibility effects.",
        "One stores seed phrases and the other stores keys.",
        "There is no difference in network behavior.",
      ],
      "They are different kinds of rule changes with different compatibility effects.",
      "The lesson focuses on compatibility and rule change mechanics.",
    ),
    createQuestion(
      "hard-forks-vs-soft-forks",
      2,
      "Why should beginners care about forks at all?",
      [
        "They help explain how network rules can evolve without ignoring coordination tradeoffs.",
        "They are required for every normal payment.",
        "They only matter to exchange marketing teams.",
      ],
      "They help explain how network rules can evolve without ignoring coordination tradeoffs.",
      "Understanding forks helps clarify how change works in decentralized systems.",
    ),
  ],
  "bitcoin-vs-other-crypto": [
    createQuestion(
      "bitcoin-vs-other-crypto",
      1,
      "What is a careful way to compare Bitcoin with other crypto assets?",
      [
        "By looking at purpose, tradeoffs, and design rather than treating them as identical.",
        "By assuming every token solves the same problem equally well.",
        "By ignoring differences in monetary policy and governance.",
      ],
      "By looking at purpose, tradeoffs, and design rather than treating them as identical.",
      "The lesson encourages comparison based on fundamentals, not labels.",
    ),
    createQuestion(
      "bitcoin-vs-other-crypto",
      2,
      "Why is Bitcoin often discussed separately from the rest of crypto?",
      [
        "Because its design priorities and monetary focus are different from many other projects.",
        "Because it is not digital.",
        "Because it depends on hidden code.",
      ],
      "Because its design priorities and monetary focus are different from many other projects.",
      "The lesson highlights Bitcoin's distinct goals and structure.",
    ),
  ],
  "why-bitcoin-is-different": [
    createQuestion(
      "why-bitcoin-is-different",
      1,
      "Why do some people say Bitcoin is different?",
      [
        "Because of its scarcity, decentralization, and credibility as money.",
        "Because it changes its supply every quarter.",
        "Because it depends on a founder-led company.",
      ],
      "Because of its scarcity, decentralization, and credibility as money.",
      "The lesson ties Bitcoin's difference to its core design choices.",
    ),
    createQuestion(
      "why-bitcoin-is-different",
      2,
      "What kind of distinction is the lesson making?",
      [
        "A distinction based on first principles, not hype alone.",
        "A distinction based only on branding.",
        "A distinction that removes the need for criticism.",
      ],
      "A distinction based on first principles, not hype alone.",
      "The goal is to ground the comparison in structure and incentives.",
    ),
  ],
  "volatility-explained": [
    createQuestion(
      "volatility-explained",
      1,
      "What does volatility mean in Bitcoin?",
      [
        "The price can move sharply up or down over short periods.",
        "The supply cap changes every week.",
        "Transactions randomly disappear.",
      ],
      "The price can move sharply up or down over short periods.",
      "Volatility is about price behavior, not a change to the protocol rules.",
    ),
    createQuestion(
      "volatility-explained",
      2,
      "What is a healthier way to respond to volatility?",
      [
        "Understand it before reacting emotionally.",
        "Assume every drop means Bitcoin has failed permanently.",
        "Ignore risk and buy without thinking.",
      ],
      "Understand it before reacting emotionally.",
      "The lesson encourages understanding rather than panic.",
    ),
  ],
  "long-term-vs-short-term-thinking": [
    createQuestion(
      "long-term-vs-short-term-thinking",
      1,
      "How does long-term thinking differ from short-term thinking?",
      [
        "It focuses more on fundamentals and time horizon than immediate price moves.",
        "It guarantees better returns every time.",
        "It avoids learning how Bitcoin works.",
      ],
      "It focuses more on fundamentals and time horizon than immediate price moves.",
      "The lesson contrasts reactive trading mindsets with deeper conviction-building.",
    ),
    createQuestion(
      "long-term-vs-short-term-thinking",
      2,
      "Why does time horizon matter?",
      [
        "It shapes how risk, volatility, and opportunity are interpreted.",
        "It changes the supply cap itself.",
        "It determines whether nodes can validate blocks.",
      ],
      "It shapes how risk, volatility, and opportunity are interpreted.",
      "Time horizon influences judgment even when the protocol stays the same.",
    ),
  ],
  "emotional-mistakes-beginners-make": [
    createQuestion(
      "emotional-mistakes-beginners-make",
      1,
      "What is a common emotional mistake beginners make?",
      [
        "Letting fear or greed drive decisions instead of understanding.",
        "Reading too much about custody.",
        "Waiting to verify a source.",
      ],
      "Letting fear or greed drive decisions instead of understanding.",
      "The lesson points to emotional reactivity as a major source of poor choices.",
    ),
    createQuestion(
      "emotional-mistakes-beginners-make",
      2,
      "What helps reduce emotional mistakes?",
      [
        "Building understanding and making decisions more deliberately.",
        "Checking the price every few minutes.",
        "Treating every rumor as urgent information.",
      ],
      "Building understanding and making decisions more deliberately.",
      "Knowledge and process help counter emotional overreaction.",
    ),
  ],
  "why-people-panic-sell": [
    createQuestion(
      "why-people-panic-sell",
      1,
      "Why do people panic sell?",
      [
        "Because sharp price moves and fear can overpower their plan.",
        "Because Bitcoin automatically forces sales.",
        "Because nodes close their wallets during downturns.",
      ],
      "Because sharp price moves and fear can overpower their plan.",
      "Panic selling is usually behavioral, not a protocol requirement.",
    ),
    createQuestion(
      "why-people-panic-sell",
      2,
      "What helps reduce panic selling?",
      [
        "Understanding volatility and having a clearer long-term framework.",
        "Reacting to every price candle immediately.",
        "Ignoring risk until losses arrive.",
      ],
      "Understanding volatility and having a clearer long-term framework.",
      "The lesson connects steadier behavior to clearer understanding.",
    ),
  ],
  "building-conviction": [
    createQuestion(
      "building-conviction",
      1,
      "What is conviction in the Bitcoin context?",
      [
        "A steadier view built from understanding rather than excitement alone.",
        "A guarantee that price cannot fall.",
        "A promise made by exchanges.",
      ],
      "A steadier view built from understanding rather than excitement alone.",
      "Conviction is presented as informed confidence, not blind certainty.",
    ),
    createQuestion(
      "building-conviction",
      2,
      "How is conviction best built?",
      [
        "By learning the underlying ideas and tradeoffs over time.",
        "By copying other people's trades without understanding them.",
        "By avoiding any view that challenges your assumptions.",
      ],
      "By learning the underlying ideas and tradeoffs over time.",
      "The lesson ties conviction to first-principles understanding.",
    ),
  ],
};
